### ISSUE TITLE
Support of Adafruit Feather STM32F405 Express

### ISSUE THREAD

**Issue by eLEcTRiCZiTy** [adafruit/Adafruit_TinyUSB_Arduino#182]
I bought a Feather board and I expected that will work with Adafruit ecosystem.
This library does not support Adafruit Feather STM32F405 Express even it have native USB.

I would like this library to support all the Adafruit products it can support.

**Comment by hathach** [comment]
hi, indeed feather stm32f405 isn't supported by this library yet. The supported cores are clearly stated in the [readme](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/blob/master/README.md). It is mostly due to
- lack of resource to do the work
- we have no control over the core. As mentioned in the readme, unlike other peripherals, USB has tightly coupled with core since Serial is expected to be available within the core. This require the arduino core changes and adopt the tinyusb source/header. Which often resolved to have an menu->usb stack option. Though this totally depends on the core maintainer.

Anyway, which stm core you are using, we can try to take a look to see how much effort needed to do the port, and also try to ask to see if the maintainer is keen to adopt such as changes.
