### ISSUE TITLE
USB host example 

### ISSUE THREAD

**Issue by deladriere** [adafruit/Adafruit_TinyUSB_Arduino#32]
Is there a way to connect a USB keyboard as a host ?

**Comment by hathach** [comment]
Can you tel me which mcu you are asking ?

**Comment by deladriere** [comment]
oops sorry, Samd21

**Comment by hathach** [comment]
the mcu support host mode, however tinyUSB host stack doesn't support SAMD just yet. Currently it only support NXP LPC OHCI/EHCI mcu. There are 2 major works to be done to support this
1. tinyUSB core driver must support samd host mode
2. This library port need to be updated to support host mode as well

Both works are pretty intense. I don't see it got supported in coming months since we have no schedule for the host mode just now.

**Comment by deladriere** [comment]
Hello @hathach any updates on the host mode ?
