### ISSUE TITLE
Cannot compile for Adafruit Feather M4 CAN (SAME51)

### ISSUE THREAD

**Issue by Callum6677** [adafruit/Adafruit_TinyUSB_Arduino#76]
Any time I compile with tinyUSB included, I simply get a nice failure to build with the following setup:
 - Adafruit Feather M4 CAN (SAME51)
 - Adafruit TinyUSB Library 0.10.1 
 - Arduino IDE 1.8.13
 - Windows 10 2002 19041
 - Any of the included TinyUSB samples
 - Board set to use TinyUSB stack

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Callum6677** [comment]
Apparently I cannot use github styling properly. Apologies.
[buildOutput.txt](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/files/6265387/buildOutput.txt)

**Comment by hathach** [comment]
> Apparently I cannot use github styling properly. Apologies.
> [buildOutput.txt](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/files/6265387/buildOutput.txt)

it is tripple backslash, though the log is too long anyway, it is best to be an txt. I will try to check this out asap.

**Comment by hathach** [comment]
I am able to reproduce the issue, it is probably due to the slight difference in macro SAMD51 SAME51 and/or other include config.  Will make an pr to fix this soon enough

**Comment by hathach** [comment]
@ladyada this issue is more involved than initial thought. The root issue is tinyusb naturally include "sam.h" which has defined of `__SAME51J19A__` which will include the correct mcu header. The issue is SAME51 is not supported by the CMSIS-Atmel package https://github.com/adafruit/ArduinoModule-CMSIS-Atmel/blob/master/CMSIS-Atmel/CMSIS/Device/ATMEL/sam.h

We tried to put the chip definition into the variant folder, however, since the tool cmsis path has higher priority in the include order (since it appears first) it is always got include. We can re-order the the include path. However, I think the proper fix should be moving mcu header into the cmsis-atmel. I will make an PR to official arduino repo, meanwhile we can use the our own tool release (possibly 1.2.1 for the next release). This will also make it much easier to add more board with same51.

**Comment by hathach** [comment]
PR to add SAME51 header to official package is on the way https://github.com/arduino/ArduinoModule-CMSIS-Atmel/pull/16

**Comment by hathach** [comment]
should be fixed by now, can you install the new bsp 1.6.7 and try again.

**Comment by Callum6677** [comment]
Working great now, that was a quick turn around, cheers
